### ISSUE TITLE
Why run pre-commit runs in CI?

### ISSUE THREAD

**Issue by jymchng** [BrianPugh/python-template#159]
As titled, would you mind sharing your insights on why are choose to include running pre-commit runs/hooks within your CI?

Thank you.

**Comment by BrianPugh** [comment]
Is the question "Why run pre-commit instead of the tools directly?" or is it "why run pre-commit in CI at all, checked in code should already pass pre-commit?"

### Why run pre-commit instead of the tools directly?
This allows all linter/other-tooling config to live in pre-commit instead of duplicating it else where. One less thing to maintain.

### Why run pre-commit in CI at all, checked in code should already pass pre-commit?
Contributors/Owners frequently forget to run `pre-commit install` or (during WIP/debugging) run `git commit --no-verify`. Re-running pre-commit in CI ensures that only properly linted/analyzed code gets merged into main. Finally, it can help catch "it ran fine on my machine" situations where something special about your local environment may have resulted in pre-commit passing.
